package com.tss.model;

public class Admin {
    private int adminId; // auto-generated by DB
    private String username;
    private String password;

    public Admin() {}

    public Admin(String username, String password) {
        this.username = username;
        this.password = password;
    }

    // Getter only - no setter for adminId
    public int getAdminId() {
        return adminId;
    }

    // This can be package-private so only DAO can set it
    public void setAdminId(int adminId) {
        this.adminId = adminId;
    }

    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }
    public void setPassword(String password) {
        this.password = password;
    }
}