package com.tss.model;

public class Employee {
    private int empId; // auto-generated by DB
    private String empName;
    private String department;
    private double plannedLeaveBalance;
    private double unplannedLeaveBalance;
    private double totalLeaveBalance;

    public Employee() {}

    public Employee(String empName, String department,
                    double plannedLeaveBalance, double unplannedLeaveBalance,
                    double totalLeaveBalance) {
        this.empName = empName;
        this.department = department;
        this.plannedLeaveBalance = plannedLeaveBalance;
        this.unplannedLeaveBalance = unplannedLeaveBalance;
        this.totalLeaveBalance = totalLeaveBalance;
    }

    // Getter only - no setter for empId
    public int getEmpId() {
        return empId;
    }

    // This can be package-private so only DAO can set it
    public void setEmpId(int empId) {
        this.empId = empId;
    }

    public String getEmpName() {
        return empName;
    }
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public String getDepartment() {
        return department;
    }
    public void setDepartment(String department) {
        this.department = department;
    }

    public double getPlannedLeaveBalance() {
        return plannedLeaveBalance;
    }
    public void setPlannedLeaveBalance(double plannedLeaveBalance) {
        this.plannedLeaveBalance = plannedLeaveBalance;
    }

    public double getUnplannedLeaveBalance() {
        return unplannedLeaveBalance;
    }
    public void setUnplannedLeaveBalance(double unplannedLeaveBalance) {
        this.unplannedLeaveBalance = unplannedLeaveBalance;
    }

    public double getTotalLeaveBalance() {
        return totalLeaveBalance;
    }
    public void setTotalLeaveBalance(double totalLeaveBalance) {
        this.totalLeaveBalance = totalLeaveBalance;
    }
}
