package com.tss.model;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class LeaveRequest {
    private int requestId;          // auto-generated by DB
    private int empId;              // foreign key from Employee table
    private String empName;         // for list view (from JOIN)
    private LocalDate startDate;
    private LocalDate endDate;
    private String reason;
    private String status;          // PENDING | APPROVED | REJECTED | CANCELLED_BY_EMPLOYEE
    private String leaveType;       // PLANNED | UNPLANNED
    private String duration;        // FULL | HALF_UPPER | HALF_LOWER
    private double numberOfDays;    // e.g., 3.0 or 0.5
    private String processedByAdmin; // admin username who processed
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public LeaveRequest() {}

    // Getters only for requestId & empId (set by DAO only)
    public int getRequestId() {
        return requestId;
    }
    public void setRequestId(int requestId) { // package-private
        this.requestId = requestId;
    }

    public int getEmpId() {
        return empId;
    }
    public void setEmpId(int empId) { // package-private
        this.empId = empId;
    }

    public String getEmpName() {
        return empName;
    }
    public void setEmpName(String empName) {
        this.empName = empName;
    }

    public LocalDate getStartDate() {
        return startDate;
    }
    public void setStartDate(LocalDate startDate) {
        this.startDate = startDate;
    }

    public LocalDate getEndDate() {
        return endDate;
    }
    public void setEndDate(LocalDate endDate) {
        this.endDate = endDate;
    }

    public String getReason() {
        return reason;
    }
    public void setReason(String reason) {
        this.reason = reason;
    }

    public String getStatus() {
        return status;
    }
    public void setStatus(String status) {
        this.status = status;
    }

    public String getLeaveType() {
        return leaveType;
    }
    public void setLeaveType(String leaveType) {
        this.leaveType = leaveType;
    }

    public String getDuration() {
        return duration;
    }
    public void setDuration(String duration) {
        this.duration = duration;
    }

    public double getNumberOfDays() {
        return numberOfDays;
    }
    public void setNumberOfDays(double numberOfDays) {
        this.numberOfDays = numberOfDays;
    }

    public String getProcessedByAdmin() {
        return processedByAdmin;
    }
    public void setProcessedByAdmin(String processedByAdmin) {
        this.processedByAdmin = processedByAdmin;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }
    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }
}
